export const videoDetail = {
  videoLink: "https://www.youtube.com/embed/Itv4FFNKG_c?si=e6wzkoAPq0VMaM1i",
  channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
  duration: "57:20",
  title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
  channelProfileSrc: require("../../../assets/images/icons/profile.png"),
  channelName: "Qazaqstan TV",
  viewsCount: "39K",
  createdAt: "9 months",
  channelSubsCnt: "2.98M",
  likeCount: "848",
  dislikeCount: "848",
  description: `Телехикаяда Алаш қайраткері Міржақып Дулатұлы өмірінің 1909-1935 жылдардағы кезеңі қамтылады. Міржақыптың «Оян, қазақ!» кітабының жарыққа шығуы, «Бақытсыз Жамал» романының жазылуы, революциядан кейінгі жылдардағы, ашаршылық кезіндегі қоғамдық-саяси қызметі, Қызылорда, Семей, Мәскеудің әйгілі «Бутырка» `,
  comments: [
    {
      userName: "@user-ee1dq6mv9v",
      comment:
        "Сегодня 10 октября 23 год, сходили с дочей в кинотеатр на просмотр этой волнующюющей картины. Зал был полный, в основном молодежь, почти пол зала как всегда захватили напитки, попкорн.",
      createdAt: "4 days",
      userProfileSrc: require("../../../assets/images/icons/profile.png"),
    },
    {
      userName: "@user-ew3tg1kr2i",
      comment:
        "Текті халқым, жаным ҚАЗАҒЫМ! Көрмегені қалмаса да адалдығы мен  бауырмалдығы, әділдігі,  тектілігі сарқылмаған   халық. Өзіміздің керемет дүниеміз көп.Осындай рухани дүние көп болсын! Көп рахмет!",
      createdAt: "3 days",
      userProfileSrc: require("../../../assets/images/icons/profile.png"),
    },
  ],
};
export const videos = [
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
];
