export const videos = [
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
];
