export const videos = [
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
];
