export const channelData = {
  profileSrc: require("../../../assets/images/icons/background.png"),
  alt: "channel-background",
};

export const channelInfo = {
  profileSrc: require("../../../assets/images/icons/profile.png"),
  name: "Qazaqstan TV",
  subscribersCount: "2.98M subscribers",
  videosCount: "67K videos",
  description: `Қазақстанның ұлттық телевизиялық каналы / &quot;Qazaqstan&quot; телеарнасы / Қазақстан ТВ /
        Қазақстан TV / Казахстан ТВ ) Qazaqstan TV – қазақстандық Youtube-тың жетекші телеарнасы.
        Әзіл, музыка, ойын-сауық, телехикаялар мен қазақстандық шоу – жазылыңыз, достарыңызбен
        бөлісіңіз! Біздің @qazaqstantv Instagram-аккаунтында байқауларға қатысып, бағалы сыйлықтар
        ұтып алыңыз!`,
  subscribed: false,
};

export const videos = [
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
  {
    thumbnailSrc: require("../../../assets/images/icons/video.png"),
    videoLink: "https://youtu.be/Itv4FFNKG_c?si=NWXRCuZJIJcPl1-7",
    channelLink: "https://youtube.com/@QazaqstanTV?si=WR0KEHcVroCsbOFj",
    duration: "57:20",
    title: "“Міржақып. Оян, қазақ!” телехикаясы. 1-бөлім ",
    channelProfileSrc: require("../../../assets/images/icons/profile.png"),
    channelName: "Qazaqstan TV",
    viewsCount: "39K Views",
    createdAt: "9 months ago",
  },
];
